package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"artemis/pkg/dsl/parser"
	"artemis/pkg/dsl/print"
)

// smallCollection is one request in one folder: enough that the old importer
// would have produced no steps at all.
const smallCollection = `{
  "info": { "name": "ping" },
  "item": [
    { "name": "Health", "item": [
      { "name": "ping", "request": { "method": "GET", "url": "https://api.test/ping" },
        "response": [{ "name": "ok", "code": 200 }] }
    ]}
  ]
}
`

// writeCollection writes src to a file in a fresh temp directory, the Postman
// counterpart of writeArt and writeYAML.
func writeCollection(t *testing.T, name, src string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// Without -o: the .art source goes to stdout, nothing goes to stderr, and no
// file is written. The importer this replaces always wrote a file, into the
// working directory, whether or not anybody asked.
func TestGeneratePrintsToStdout(t *testing.T) {
	path := writeCollection(t, "ping.postman_collection.json", smallCollection)

	stdout, stderr, err := executeArgs(t, "generate", "-f", path)
	if err != nil {
		t.Fatalf("Execute() = %v, want nil\nstderr:\n%s", err, stderr)
	}
	want := `# Generated by artemis generate from ping.postman_collection.json.
scenario "ping" {
  step "Health / ping" {
    get "https://api.test/ping"
    expect status == 200
  }
}
`
	if stdout != want {
		t.Errorf("stdout =\n%s\nwant\n%s", stdout, want)
	}
	if stderr != "" {
		t.Errorf("stderr = %q, want nothing", stderr)
	}

	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Errorf("the directory holds %d files, want only the collection: generate wrote one uninvited", len(entries))
	}
}

// -o writes the file and prints nothing, so a generation that is redirected
// and one that is written to a path produce the same bytes.
func TestGenerateWritesTheFileWithOut(t *testing.T) {
	path := writeCollection(t, "ping.postman_collection.json", smallCollection)
	out := filepath.Join(filepath.Dir(path), "ping.art")

	stdout, stderr, err := executeArgs(t, "generate", "-f", path, "-o", out)
	if err != nil {
		t.Fatalf("Execute() = %v, want nil\nstderr:\n%s", err, stderr)
	}
	if stdout != "" || stderr != "" {
		t.Errorf("stdout = %q, stderr = %q, want nothing: -o writes to the file", stdout, stderr)
	}

	written, err := os.ReadFile(out) //nolint:gosec // a path this test named
	if err != nil {
		t.Fatal(err)
	}
	piped, _, err := executeArgs(t, "generate", "-f", path)
	if err != nil {
		t.Fatal(err)
	}
	if string(written) != piped {
		t.Errorf("the file holds\n%s\nand stdout held\n%s", written, piped)
	}
}

// The clobber guard. The importer this replaces derived its own filename and
// wrote it into the working directory, so running it twice in a repo replaced
// a file somebody had since edited with no warning and no way to say
// otherwise.
func TestGenerateRefusesToClobberWithoutForce(t *testing.T) {
	path := writeCollection(t, "ping.postman_collection.json", smallCollection)
	out := filepath.Join(filepath.Dir(path), "ping.art")
	const mine = "# my own file\nscenario \"mine\" {\n}\n"
	if err := os.WriteFile(out, []byte(mine), 0o600); err != nil {
		t.Fatal(err)
	}

	_, _, err := executeArgs(t, "generate", "-f", path, "-o", out)
	if err == nil {
		t.Fatal("Execute() = nil, want an error")
	}
	if !strings.Contains(err.Error(), "--force") || !strings.Contains(err.Error(), "ping.art") {
		t.Errorf("error = %v, want the file and --force named", err)
	}

	on, err := os.ReadFile(out) //nolint:gosec // a path this test wrote
	if err != nil {
		t.Fatal(err)
	}
	if string(on) != mine {
		t.Errorf("the file changed:\n%s", on)
	}
}

// --force is the way to say so, and then the file is replaced.
func TestGenerateForceReplacesTheFile(t *testing.T) {
	path := writeCollection(t, "ping.postman_collection.json", smallCollection)
	out := filepath.Join(filepath.Dir(path), "ping.art")
	if err := os.WriteFile(out, []byte("# was here\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if _, stderr, err := executeArgs(t, "generate", "-f", path, "-o", out, "--force"); err != nil {
		t.Fatalf("Execute() = %v, want nil\nstderr:\n%s", err, stderr)
	}

	on, err := os.ReadFile(out) //nolint:gosec // a path this test named
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(on), `step "Health / ping"`) {
		t.Errorf("the file was not replaced:\n%s", on)
	}
}

// An error returns rather than being logged and walked past. The version this
// replaces was a `Run` that logged each failure and carried on, so a
// collection that would not parse was followed by a conversion of the zero
// value and the process still exited 0.
func TestGenerateReturnsItsErrors(t *testing.T) {
	cases := []struct {
		name, file, want string
		collection       string
	}{{
		name:       "a file that is not a collection",
		file:       "broken.json",
		collection: `{"info":`,
		want:       "broken.json",
	}, {
		name:       "a formdata body",
		file:       "form.json",
		collection: `{"info":{"name":"c"},"item":[{"name":"up","request":{"method":"POST","url":"https://api.test/u","body":{"mode":"formdata","formdata":[]}}}]}`,
		want:       `"up"`,
	}, {
		name:       "an auth type with no DSL spelling",
		file:       "oauth.json",
		collection: `{"info":{"name":"c"},"auth":{"type":"oauth2","oauth2":[]},"item":[{"name":"p","request":{"method":"GET","url":"https://api.test/p"}}]}`,
		want:       "oauth2",
	}, {
		name:       "a dynamic variable",
		file:       "guid.json",
		collection: `{"info":{"name":"c"},"item":[{"name":"p","request":{"method":"GET","url":"https://api.test/{{$guid}}"}}]}`,
		want:       "dynamic variable",
	}}

	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			path := writeCollection(t, c.file, c.collection)

			stdout, _, err := executeArgs(t, "generate", "-f", path)
			if err == nil {
				t.Fatalf("Execute() = nil, want an error\nstdout:\n%s", stdout)
			}
			if !strings.Contains(err.Error(), c.want) {
				t.Errorf("error = %v, want %q in it", err, c.want)
			}
			if stdout != "" {
				t.Errorf("stdout = %q, want nothing: a refused collection writes no source", stdout)
			}
		})
	}
}

// A failed generation writes no file either, so a half-converted collection
// cannot land on disk.
func TestGenerateWritesNothingWhenItRefuses(t *testing.T) {
	path := writeCollection(t, "guid.json",
		`{"info":{"name":"c"},"item":[{"name":"p","request":{"method":"GET","url":"https://api.test/{{$guid}}"}}]}`)
	out := filepath.Join(filepath.Dir(path), "out.art")

	if _, _, err := executeArgs(t, "generate", "-f", path, "-o", out); err == nil {
		t.Fatal("Execute() = nil, want an error")
	}
	if _, err := os.Stat(out); err == nil {
		t.Error("the file was written anyway")
	}
}

// The extension guards. Saying so is better than reading a .art file as JSON
// and reporting a syntax error in it, and better still than writing .art
// source into a file called .yaml.
func TestGenerateRefusesTheWrongExtensions(t *testing.T) {
	collection := writeCollection(t, "c.json", smallCollection)

	cases := []struct{ name, file, out, want string }{
		{"a .art input", writeArt(t, "x.art", cleanArt), "", "artemis fmt"},
		{"a .yaml input", writeCollection(t, "x.yaml", "name: x\n"), "", "artemis migrate"},
		{"a .yaml output", collection, "out.yaml", "is not one"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			args := []string{"generate", "-f", c.file}
			if c.out != "" {
				args = append(args, "-o", filepath.Join(t.TempDir(), c.out))
			}
			_, _, err := executeArgs(t, args...)
			if err == nil {
				t.Fatal("Execute() = nil, want an error")
			}
			if !strings.Contains(err.Error(), c.want) {
				t.Errorf("error = %v, want %q in it", err, c.want)
			}
		})
	}
}

// goldenCollection is the fixture the done-when names: nested folders, headers,
// query parameters, a non-JSON body, every auth type that translates, and a
// variable that has to be renamed.
const goldenCollection = "testdata/postman/kitchen_sink.postman_collection.json"

// TestGoldenPostmanGenerate pins the whole of a generation rather than the
// lines a test happens to assert on. Named for `make golden`, which runs
// `-run TestGolden -update` over this package.
func TestGoldenPostmanGenerate(t *testing.T) {
	stdout, stderr, err := executeArgs(t, "generate", "-f", goldenCollection)
	if err != nil {
		t.Fatalf("Execute() = %v, want nil\nstderr:\n%s", err, stderr)
	}

	path := filepath.Join("testdata", "postman", "kitchen_sink.art")
	if *update {
		if err := os.WriteFile(path, []byte(stdout), 0o600); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path) //nolint:gosec // a path this test built
	if err != nil {
		t.Fatalf("%v\nrun `make golden` and read the diff", err)
	}
	if stdout != string(want) {
		t.Errorf("generating %s gave\n%s\nthe golden holds\n%s", goldenCollection, stdout, want)
	}
}

// The done-when's first half: the generated file parses and checks clean, with
// no diagnostics at all. A generated scenario artemis would refuse is an
// importer nobody can adopt.
func TestGeneratedGoldenChecksClean(t *testing.T) {
	src, err := os.ReadFile(filepath.Join("testdata", "postman", "kitchen_sink.art"))
	if err != nil {
		t.Fatal(err)
	}

	bag := frontEnd("kitchen_sink.art", string(src)).Bag
	if bag.HasErrors() {
		for _, d := range bag.All() {
			t.Errorf("%s: %s", d.Code, d.Message)
		}
	}
}

// And its second: the output is already canonical, so `artemis fmt` would not
// change a generated file. This is what "through the same canonical printer"
// means in practice.
func TestGeneratedGoldenIsCanonical(t *testing.T) {
	path := filepath.Join("testdata", "postman", "kitchen_sink.art")
	src, err := os.ReadFile(path) //nolint:gosec // a path this test built
	if err != nil {
		t.Fatal(err)
	}

	tree, bag := parser.Parse(path, string(src))
	if bag.HasErrors() {
		t.Fatalf("the golden does not parse: %v", bag.All()[0])
	}
	if got := print.Canonical(tree); got != string(src) {
		t.Errorf("the golden is not canonical; artemis fmt would write\n%s", got)
	}
}

// The folder walk, read off the golden: every request in the fixture is a step,
// in collection order, and the empty folder is not.
func TestGoldenCoversEveryRequest(t *testing.T) {
	src, err := os.ReadFile(filepath.Join("testdata", "postman", "kitchen_sink.art"))
	if err != nil {
		t.Fatal(err)
	}

	want := []string{
		`step "Health / ping"`,
		`step "Orders / Admin / list orders"`,
		`step "Orders / create order"`,
		`step "Orders / amend order"`,
		`step "Orders / search orders"`,
		`step "Legacy / raw header form"`,
	}
	at := -1
	for _, w := range want {
		i := strings.Index(string(src), w)
		if i < 0 {
			t.Errorf("%s is missing from the golden", w)
			continue
		}
		if i < at {
			t.Errorf("%s is out of collection order", w)
		}
		at = i
	}
	for _, gone := range []string{"Empty folder", "X-Trace", "cursor", "void", "retry"} {
		if strings.Contains(string(src), gone) {
			t.Errorf("%q should not be in the golden", gone)
		}
	}
}
