package postman

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path/filepath"
	"strings"

	"artemis/pkg/shared/migrate"
)

// okStatus is the bound a request with no saved example response asserts
// against: `expect status < 400`.
//
// The old importer wrote `status_code: 200` on every step, which is a guess
// that fails on every 201 and every 204. Postman records no expected status
// unless the author saved an example, so this is the strongest honest claim --
// and still a real assertion, where emitting none would give a generated suite
// that passes while checking nothing.
const okStatus = 400

// Translate is collection as the shape migrate.Source translates.
//
// source is the collection's file name, which goes into the generated file's
// first comment: a .art file somebody finds in a repo a year later should say
// where it came from.
//
// An error means the collection holds something with no DSL spelling and names
// the request it was in. Nothing partial is returned.
func Translate(c Collection, source string) (migrate.Config, migrate.Comments, error) {
	n, err := resolve(c)
	if err != nil {
		return migrate.Config{}, migrate.Comments{}, err
	}

	config := migrate.Config{
		Name:      scenarioName(c, source),
		Type:      "functional",
		Variables: variables(c, n),
		Steps:     make([]migrate.Step, 0, len(c.Items)),
	}

	steps, err := walkItems(c.Items, nil, c.Auth, n)
	if err != nil {
		return migrate.Config{}, migrate.Comments{}, err
	}
	config.Steps = steps

	return config, migrate.Comments{File: fileComment(source, n)}, nil
}

// scenarioName is the scenario's name: the collection's, or the file's stem
// when the collection did not name itself. `scenario ""` parses, and is a
// report nobody can read.
func scenarioName(c Collection, source string) string {
	if name := strings.TrimSpace(c.Info.Name); name != "" {
		return name
	}
	base := filepath.Base(source)
	if stem := strings.TrimSuffix(base, filepath.Ext(base)); stem != "" && stem != "." {
		return stem
	}
	return "collection"
}

// variables is the `var` lines the scenario opens with: the collection's own
// variables under their DSL names, then one per undeclared placeholder reading
// the environment.
func variables(c Collection, n names) []migrate.Variable {
	out := make([]migrate.Variable, 0, len(c.Variables)+len(n.undeclared))
	seen := map[string]bool{}
	for _, v := range c.Variables {
		if v.Disabled || v.Key == "" {
			continue
		}
		name := n.rename[v.Key]
		if name == "" || seen[name] {
			continue
		}
		seen[name] = true
		out = append(out, migrate.Variable{Name: name, Value: n.apply(v.Value)})
	}
	for _, ident := range n.undeclared {
		if seen[ident] {
			continue
		}
		seen[ident] = true
		// `{{env.NAME}}` is the spelling migrate turns into the bare call
		// env("NAME"), so the var line reads `var token = env("TOKEN")`.
		out = append(out, migrate.Variable{Name: ident, Value: "{{env." + envName(ident) + "}}"})
	}
	return out
}

// fileComment is the block above `scenario`: where the file came from, and
// every name the importer had to change or invent.
//
// Both notes are things the reader has to know and cannot see from the output:
// that `base_url` was `base-url` in Postman, and that `access_token` is now
// read from the environment rather than from the collection.
func fileComment(source string, n names) string {
	lines := []string{"# Generated by artemis generate from " + filepath.Base(source) + "."}
	for _, key := range n.renamed {
		lines = append(lines, fmt.Sprintf("# The Postman variable %q is written %s here, because %s.",
			key, n.rename[key], renameReason(key)))
	}
	if len(n.undeclared) > 0 {
		quoted := make([]string, 0, len(n.undeclared))
		for _, ident := range n.undeclared {
			quoted = append(quoted, ident+" from "+envName(ident))
		}
		lines = append(lines, "# Read from the environment, because the collection used them without defining them: "+
			strings.Join(quoted, ", ")+".")
	}
	return strings.Join(lines, "\n")
}

// renameReason says why a key could not be written as it was, for the file
// comment. The three reasons are the three branches of identifier(): a
// character a name cannot hold, a leading digit, and a reserved word.
func renameReason(key string) string {
	for i := 0; i < len(key); i++ {
		c := key[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c == '_', c >= '0' && c <= '9':
		default:
			return fmt.Sprintf("a DSL name cannot hold %q", string(c))
		}
	}
	if key != "" && key[0] >= '0' && key[0] <= '9' {
		return "a DSL name cannot start with a digit"
	}
	return "the DSL reserves that word"
}

// walkItems is the folder walk: depth first, in collection order, one step per
// item that carries a request.
//
// This is the repair the issue is named for. The old importer looped over the
// top level only and read `item.request` off whatever it found, so a collection
// whose requests sat in folders -- which is every collection of any size --
// produced one step per folder, each with an empty URL and an empty method, and
// no step at all for any of the requests.
//
// auth is the auth in force at this depth: the collection's at the top, and a
// request's own overrides it. A folder may not carry auth in the shapes this
// package reads, so it is passed through unchanged.
func walkItems(items []Item, path []string, auth *Auth, n names) ([]migrate.Step, error) {
	var out []migrate.Step
	for i := range items {
		it := items[i]
		here := append(append([]string{}, path...), it.Name)

		if it.Request != nil {
			s, err := translateStep(it, here, auth, n)
			if err != nil {
				return nil, err
			}
			out = append(out, s)
		}
		nested, err := walkItems(it.Items, here, auth, n)
		if err != nil {
			return nil, err
		}
		out = append(out, nested...)
	}
	return out, nil
}

// stepName is the item's folder path and its own name, joined. The DSL has no
// nesting below `scenario`, so the tree has to flatten; keeping the path is
// what distinguishes two requests both called "create" in a report.
func stepName(path []string) string {
	parts := make([]string, 0, len(path))
	for _, p := range path {
		if p = strings.TrimSpace(p); p != "" {
			parts = append(parts, p)
		}
	}
	if len(parts) == 0 {
		return "request"
	}
	return strings.Join(parts, " / ")
}

// translateStep is one request as an api step.
func translateStep(it Item, path []string, auth *Auth, n names) (migrate.Step, error) {
	name := stepName(path)
	r := it.Request

	if r.Auth != nil {
		auth = r.Auth
	}

	rawURL, query := splitURL(r.URL, n)
	headers, authQuery, err := headerFields(r, auth, n)
	if err != nil {
		return migrate.Step{}, fmt.Errorf("request %q: %w", name, err)
	}
	query = append(query, authQuery...)

	body, contentType, err := requestBody(r.Body, n)
	if err != nil {
		return migrate.Step{}, fmt.Errorf("request %q: %w", name, err)
	}
	// Postman sends a Content-Type derived from the body's mode when the
	// request declares none. The old importer wrote one unconditionally, so a
	// form-encoded or plain-text body was announced as JSON.
	if contentType != "" && !hasHeader(headers, "Content-Type") {
		headers = append(headers, migrate.Param{Name: "Content-Type", Value: contentType})
	}

	code, op := status(it)

	return migrate.Step{
		Name: name,
		// Set explicitly: migrate.action reads it to decide which action block
		// to write, and every Postman item is an HTTP request.
		Type: "api",
		Request: migrate.Request{
			URL:        rawURL,
			Method:     method(r),
			HeaderList: headers,
			Query:      query,
			Body:       body,
		},
		Response: migrate.Response{StatusCode: code, StatusOp: op},
		// No Retry, deliberately: a collection says nothing about retrying a
		// request, so neither does the file generated from one.
	}, nil
}

// method is the request's verb, upper or lower as Postman wrote it. migrate's
// own request() lowercases it, checks it against token.IsMethod and defaults an
// empty one to GET, so there is nothing to validate here.
func method(r *Request) string {
	return strings.TrimSpace(r.Method)
}

// splitURL is the request's URL and its query parameters, separated.
//
// When the URL object carries a `query` array, the query string is stripped off
// the raw URL: lowering appends the step's `query` fields to whatever the URL
// already has, so leaving both would send every parameter twice. When it does
// not -- a URL written as a plain string -- the raw URL keeps its query string
// and no `query` fields are emitted, which is the same request by a different
// spelling.
func splitURL(u URL, n names) (string, []migrate.Param) {
	raw := strings.TrimSpace(u.Raw)
	if raw == "" {
		raw = joinURL(u)
	}

	var query []migrate.Param
	for _, e := range u.Query {
		if e.Disabled || e.Key == "" {
			continue
		}
		query = append(query, migrate.Param{Name: n.apply(e.Key), Value: n.apply(e.Value)})
	}
	if len(query) > 0 {
		if i := strings.Index(raw, "?"); i >= 0 {
			raw = raw[:i]
		}
	}
	return n.apply(raw), query
}

// joinURL rebuilds a URL from the parts, for a collection that wrote them
// without a `raw`. Postman always writes `raw` in practice; this is here so
// that one that does not produces a URL rather than an empty string.
func joinURL(u URL) string {
	var b strings.Builder
	if u.Protocol != "" {
		b.WriteString(u.Protocol + "://")
	}
	b.WriteString(strings.Join(u.Host, "."))
	if len(u.Path) > 0 {
		b.WriteString("/" + strings.Join(u.Path, "/"))
	}
	return b.String()
}

// headerFields is the request's headers in the order they are sent, plus any
// query parameter the auth block contributes.
//
// Auth comes first and the request's own headers after it, so a request that
// writes its own `Authorization` wins -- the DSL sends both and the last one
// is what a server reads. A disabled header is skipped: the author switched it
// off, and importing a collection must not switch it back on.
func headerFields(r *Request, auth *Auth, n names) (headers []migrate.Param, query []migrate.Param, err error) {
	headers, query, err = authFields(auth, n)
	if err != nil {
		return nil, nil, err
	}
	for _, e := range r.Header {
		if e.Disabled || e.Key == "" {
			continue
		}
		headers = append(headers, migrate.Param{Name: n.apply(e.Key), Value: n.apply(e.Value)})
	}
	return headers, query, nil
}

// authFields is an auth block as header and query fields.
//
// There is no scenario-level default header block in the DSL, so a
// collection-level auth is repeated on every step. That is verbose and it is
// also exactly what the collection means; a reader can lift it into a variable
// afterwards.
func authFields(a *Auth, n names) (headers []migrate.Param, query []migrate.Param, err error) {
	if a == nil || a.Type == "" || a.Type == AuthNone {
		return nil, nil, nil
	}

	switch a.Type {
	case AuthBearer:
		token := n.apply(a.Param("token"))
		return []migrate.Param{{Name: "Authorization", Value: "Bearer " + token}}, nil, nil

	case AuthBasic:
		user, pass := a.Param("username"), a.Param("password")
		if strings.Contains(user+pass, "{{") {
			return nil, nil, fmt.Errorf("basic auth uses a {{placeholder}} in its credentials, and there is no " +
				"base64() in the DSL to defer the encoding to; set a literal username and password, or move the " +
				"whole header into the request as `Authorization: Basic <encoded>`")
		}
		encoded := base64.StdEncoding.EncodeToString([]byte(user + ":" + pass))
		return []migrate.Param{{Name: "Authorization", Value: "Basic " + encoded}}, nil, nil

	case AuthAPIKey:
		key, value := n.apply(a.Param("key")), n.apply(a.Param("value"))
		if key == "" {
			return nil, nil, fmt.Errorf("apikey auth names no key")
		}
		if strings.EqualFold(a.Param("in"), "query") {
			return nil, []migrate.Param{{Name: key, Value: value}}, nil
		}
		return []migrate.Param{{Name: key, Value: value}}, nil, nil

	default:
		return nil, nil, fmt.Errorf("auth type %q has no DSL spelling: bearer, basic and apikey translate to a "+
			"header, and the rest need a signature artemis does not compute", a.Type)
	}
}

// hasHeader reports whether the list already names a header, case-insensitively
// as HTTP compares them.
func hasHeader(headers []migrate.Param, name string) bool {
	for _, h := range headers {
		if strings.EqualFold(h.Name, name) {
			return true
		}
	}
	return false
}

// requestBody is the body as text migrate.requestBody will translate, plus the
// Content-Type the mode implies.
//
// The body is returned as a string because that is what migrate.Request holds;
// a `raw` body that parses as JSON becomes an object or array literal there,
// which is the thing the old importer's text concatenation could not do.
func requestBody(b *Body, n names) (body, contentType string, err error) {
	if b == nil || b.Disabled || b.Mode == "" || b.Mode == ModeNone {
		return "", "", nil
	}

	switch b.Mode {
	case ModeRaw:
		return n.apply(b.Raw), rawContentType(b.Language()), nil

	case ModeURLEncoded:
		form := url.Values{}
		for _, e := range b.URLEncoded {
			if e.Disabled || e.Key == "" {
				continue
			}
			form.Add(n.apply(e.Key), n.apply(e.Value))
		}
		if len(form) == 0 {
			return "", "", nil
		}
		return form.Encode(), "application/x-www-form-urlencoded", nil

	case ModeGraphQL:
		doc, err := graphQLBody(b.GraphQL, n)
		if err != nil {
			return "", "", err
		}
		return doc, "application/json", nil

	case ModeFormData:
		return "", "", fmt.Errorf("a formdata body is multipart, which artemis has no request field for; " +
			"send the same data as a raw or urlencoded body, or leave this request out")

	case ModeFile:
		return "", "", fmt.Errorf("a file body reads a file from disk at send time, which artemis has no request " +
			"field for; inline the content as a raw body")

	default:
		return "", "", fmt.Errorf("body mode %q is not one artemis knows", b.Mode)
	}
}

// rawContentType is what Postman sends for a raw body of the given language.
// An undeclared language means no header: Postman sends the body with whatever
// the request's own headers say, and inventing `application/json` for it is the
// bug this replaces.
func rawContentType(language string) string {
	switch strings.ToLower(language) {
	case "json":
		return "application/json"
	case "xml":
		return "application/xml"
	case "html":
		return "text/html"
	case "javascript":
		return "application/javascript"
	case "text":
		return "text/plain"
	default:
		return ""
	}
}

// graphQLBody is a graphql body as the JSON object Postman sends: the document
// and its variables. It is built with encoding/json so the document's newlines
// and quotes are escaped once, by the library, rather than by hand.
func graphQLBody(g *GraphQL, n names) (string, error) {
	if g == nil {
		return "", nil
	}
	doc := map[string]any{"query": n.apply(g.Query)}
	if raw := strings.TrimSpace(string(g.Variables)); raw != "" && raw != "null" {
		var vars any
		// Postman writes variables as an object, or as a string holding one.
		if s, ok := jsonString(g.Variables); ok {
			raw = n.apply(s)
		} else {
			raw = n.apply(raw)
		}
		if err := json.Unmarshal([]byte(raw), &vars); err != nil {
			return "", fmt.Errorf("the graphql variables are not JSON: %w", err)
		}
		doc["variables"] = vars
	}
	out, err := json.Marshal(doc)
	if err != nil {
		return "", err
	}
	return string(out), nil
}

// status is the step's status assertion: the code and the comparison.
//
// A saved example response is the only thing in a collection that says what a
// request should return, so its code is asserted exactly. A request with none
// asserts `status < 400`; see okStatus.
func status(it Item) (code int, op string) {
	for _, r := range it.Response {
		if r.Code > 0 {
			return r.Code, ""
		}
	}
	return okStatus, "<"
}
